name: SauceDemo UI Tests

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: saucedemo-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: saucedemo-tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: saucedemo-tests/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run tests (headless) + HTML report
        run: |
          pytest -q --html=reports/report.html --self-contained-html

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: sauce-demo-report
          path: saucedemo-tests/reports/report.html
          if-no-files-found: error
